name: PHPUnit
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          extensions: "mbstring"
          coverage: xdebug

      - name: "Install Composer dependencies & app config"
        run: composer install --no-progress --no-interaction

      - name: "Execute unit tests"
        run: vendor/bin/phpunit --coverage-html coverage --coverage-clover 'coverage/clover.xml'

      - name: "Upload test coverage"
        uses: actions/upload-artifact@v3
        with:
          name: Test Coverage Report
          path: ./coverage/

      - name: "Comment coverage report"
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage/clover.xml

      - name: Generate coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          report: coverage/clover.xml

      - name: "Retrieve the logs"
        if: ${{ failure() }}
        run: cat storage/logs/*
